CREATE TABLE class(Name CHAR(20),ID INT);
INSERT INTO class VALUES('Johnson',100);
INSERT INTO class VALUES('Kiran',102);
INSERT INTO class VALUES('Sachin',105);
INSERT INTO class VALUES('Rahul',109);
SELECT * FROM class;
INSERT INTO class VALUES('JOseph;,110);
COMMIT;
SELECT * FROM class;
INSERT INTO class VALUES('Joseph',110);
ROLLBACK;
SELECT * FROM class;
SAVEPOINT A;
DELETE FROM class WHERE ID=102;
SAVEPOINT B;
DELETE FROM class WHERE ID=100;
SAVEPOINT C;
DELETE FROM class WHERE ID=105;
SELECT * FROM class;
ROLLBACK TO B;
SELECT * FROM class;





